### ISSUE TITLE
How could I get the document "tot/data/bamboogle/train.json"? Could you get me a chain of this project?

### ISSUE THREAD

**Issue by Haodong-Lei-Ray** [sail-sg/CPO#1]

**Comment by jadeCurl** [comment]
We use the data from the Compositional Celebrities dataset as the training set for the Bamboogle task, as it consists entirely of compositional 2-hop QA questions. You can find both the Bamboogle dataset and the Compositional Celebrities dataset here: https://github.com/ofirpress/self-ask/tree/main/datasets.
