### ISSUE TITLE
About this work and Step-DPO

### ISSUE THREAD

**Issue by Ignoramus0817** [sail-sg/CPO#3]
What's the difference between this work and `Step-DPO: Step-wise Preference Optimization for Long-chain Reasoning of LLMs`(https://arxiv.org/abs/2406.18629) ?
From my perspective, they are almost the same considering motivation and methodology.

**Comment by zhangxxxx0** [comment]
CPO was submitted on June 13, while Step-DPO was submitted on June 26. Both were developed independently. I’m not sure what your problem is.

**Comment by Ignoramus0817** [comment]
Nevermind, just mistaken the appearing date of Step-DPO as Jan.
